### ISSUE TITLE
joinkey not found cluster join failed ECONN error

### ISSUE THREAD

**Issue by mreddy93** [jfrog/charts#1289]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

**Which chart**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by mreddy93** [comment]
im using artifactory-pro helm chart i have created secrets before and given those secrets in values.yaml

**Comment by chukka** [comment]
@mreddy93 can you share below information :



Version of Helm and Kubernetes:

Which chart:

What happened:

What you expected to happen:

How to reproduce it (as minimally and precisely as possible):

Anything else we need to know:

**Comment by mreddy93** [comment]
Version of Helm and Kubernetes: helm-3.4/k8s:v.19.4 

Which chart: artifactory

What happened: cluster join failed ECONN error

What you expected to happen: expected succesful creation of pods 

How to reproduce it (as minimally and precisely as possible):

Anything else we need to know:
do i need to change anything in system.yaml ?

**Comment by abhinavkhanna-sf** [comment]
@rahulsadanandan @chukka any update on this?
I am getting the same error.

Can you please confirm the location of join.key file?

is it 

```
/var/opt/jfrog/artifactory/etc/security/join.key 
https://jfrog.com/knowledge-base/how-to-troubleshoot-artifactory-7-x-upgrade-issues/
```
or
```
/var/opt/jfrog/artifactory/bootstrap/access/etc/security/join.key
```
```
echo -n ${ARTIFACTORY_JOIN_KEY} > {{ .Values.artifactory.persistence.mountPath }}/bootstrap/access/etc/security/join.key;
```
from
https://github.com/jfrog/charts/blob/bd3f0b1c5e22f0bb6f95291733981d80e3f20d24/stable/artifactory/templates/artifactory-statefulset.yaml#L178

**Comment by chukka** [comment]
@abhinavkhanna-sf  `/var/opt/jfrog/artifactory/bootstrap/access/etc/security/join.key` is the boostrap location of the file and it will copy to `/var/opt/jfrog/artifactory/etc/security/join.key ` on artifactory start.

Can you share logs to debug further ?

**Comment by abhinavkhanna-sf** [comment]
@chukka thanks for getting back. I think I am good now. After retrying looking for join.key for 2 minutes, it picks the bootstrap file in my case.

**Comment by abhinavkhanna-sf** [comment]
@chukka one thing i have notice is whenever I to try to set admin credential. It gives this error and does not recover from missing join.key error

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.jersey.JerseyAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jerseyConfig' defined in URL [jar:file:/opt/jfrog/artifactory/app/artifactory/tomcat/webapps/access/WEB-INF/lib/access-application-7.25.0.jar!/org/jfrog/access/rest/config/JerseyConfig.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jfrog.access.rest.config.JerseyConfig]: Constructor threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'systemResource' defined in URL [jar:file:/opt/jfrog/artifactory/app/artifactory/tomcat/webapps/access/WEB-INF/lib/access-server-rest-7.25.0.jar!/org/jfrog/access/server/rest/resource/system/SystemResource.class]: Unsatisfied dependency expressed through constructor parameter 4; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accessServerBootstrapImpl': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Illegal credentials file - each line is expected to be in the format: user=pass
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:410)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213)
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:212)
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:203)
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addServletContextInitializerBeans(ServletContextInitializerBeans.java:97)
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:86)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getServletContextInitializerBeans(ServletWebServerApplicationContext.java:259)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:233)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:190)
	at org.springframework.boot.web.s
	```
	This is my admin settings in values. yaml
	```
admin:
        ip: "*"
        username: "admin"
        secret: artifactory-admin-creds
        dataKey: password
```

**Comment by chukka** [comment]
@abhinavkhanna-sf  is this still an issue ?Can this be raised as separate issue , I'm marking this as closed

**Comment by jnimmy** [comment]
am facing "Cluster join: Join key is missing. Pending for 150 seconds with 5m0s timeout" help me here

**Comment by jnimmy** [comment]
Testing directory /var/opt/jfrog/router has read/write permissions for user id 1001020000
Permissions for /var/opt/jfrog/router are good
Setting JF_SHARED_NODE_ID to artifactory-0
Setting JF_SHARED_NODE_IP to 10.128.2.43
Setting JF_SHARED_NODE_NAME to artifactory-0
Using default router's certificate and private key
======= Router PID 264
/opt/jfrog/router/app/bin/entrypoint-router.sh: line 112: /opt/jfrog/router/app/router/router.pid: Permission denied
Logging configuration has both console=true and filepath='router-service.log'; ignoring console.
2024-03-08T11:59:19.202Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [bootstrap.go:91               ] [main                ] [] - Router (jfrou) service initialization started. Version: 7.91.0-1 Revision: ec27a5a93ecc099895ef9bcb50c948bba1d00e4d PID: 264 Home: /opt/jfrog/router
2024-03-08T11:59:19.202Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [bootstrap.go:94               ] [main                ] [] - JFrog Router IP: 10.128.2.43
2024-03-08T11:59:19.203Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [bootstrap.go:95               ] [main                ] [] - Effective configuration:
access.database.maxOpenConnections (File): 80
access.http.port (Default Value): 8040
access.tomcat.connector.extraConfig (File): acceptCount="100"
access.tomcat.connector.maxThreads (File): 50
access.tomcat.connector.sendReasonPhrase (File): false
artifactory.database.maxOpenConnections (File): 80
artifactory.tomcat.connector.extraConfig (File): acceptCount="400"
artifactory.tomcat.connector.maxThreads (File): 200
artifactory.tomcat.connector.sendReasonPhrase (File): false
artifactory.tomcat.maintenanceConnector.port (File): 8091
federation.enabled (File): false
frontend.session.timeMinutes (File): 30
jfconnect.enabled (File): true
metadata.database.maxOpenConnections (File): 80
product.data.internal (Environment Variable: JF_PRODUCT_DATA_INTERNAL): /var/opt/jfrog/router
product.home (Environment Variable: JF_PRODUCT_HOME): /opt/jfrog/router
router.autoMemLimitRatio (Default Value): 0.9
router.encryptSystemConfig (Default Value): true
router.entrypoints.externalHost (Default Value): 
router.entrypoints.externalMaxConcurrentStreams (Default Value): 500
router.entrypoints.externalPort (Default Value): 8082
router.entrypoints.grpcPort (Default Value): 8047
router.entrypoints.internalMaxConcurrentStreams (Default Value): 500
router.entrypoints.internalPort (Default Value): 8046
router.entrypoints.traefikApiPort (Default Value): 8049
router.httpclient.requestTimeoutSecs (Default Value): 30
router.lifecycle.shutdown.entrypointsGraceTimeout (Default Value): 10s
router.lifecycle.shutdown.internalJobsGraceTimeout (Default Value): 7s
router.logging.application.caller (Default Value): false
router.logging.application.console (Default Value): true
router.logging.application.filePath (Default Value): router-service.log
router.logging.application.format (Default Value): jftext
router.logging.application.level (Default Value): info
router.logging.application.rotation.compress (Default Value): true
router.logging.application.rotation.keepLastDecompressed (Default Value): 1
router.logging.application.rotation.maxAgeDays (Default Value): 0
router.logging.application.rotation.maxFiles (Default Value): 10
router.logging.application.rotation.maxSizeMb (Default Value): 25
router.logging.consoleLog.format (Default Value): jftext
router.logging.request.filePath (Default Value): router-request.log
router.logging.request.forwardedForLogging.enabled (Default Value): false
router.logging.request.forwardedForLogging.header (Default Value): X-Forwarded-For
router.logging.request.rotation.compress (Default Value): true
router.logging.request.rotation.keepLastDecompressed (Default Value): 1
router.logging.request.rotation.maxAgeDays (Default Value): 0
router.logging.request.rotation.maxFiles (Default Value): 10
router.logging.request.rotation.maxSizeMb (Default Value): 100
router.logging.request.tokenIdLoggingEnabled (Default Value): false
router.logging.request.verbose (Default Value): false
router.logging.traefik.caller (Default Value): false
router.logging.traefik.console (Default Value): true
router.logging.traefik.filePath (Default Value): router-traefik.log
router.logging.traefik.format (Default Value): jftext
router.logging.traefik.level (Default Value): info
router.logging.traefik.rotation.compress (Default Value): true
router.logging.traefik.rotation.keepLastDecompressed (Default Value): 1
router.logging.traefik.rotation.maxAgeDays (Default Value): 0
router.logging.traefik.rotation.maxFiles (Default Value): 10
router.logging.traefik.rotation.maxSizeMb (Default Value): 25
router.masterKeyRemoval.heartbeatCount (Default Value): 3
router.masterKeyRemoval.intervalSecs (Default Value): 60
router.masterKeyRemoval.timeoutSecs (Default Value): 600
router.mtls.configCacheExpirationSecs (Default Value): 600
router.multiTenant.cacheExpirySecs (Default Value): 86400
router.multiTenant.cacheGcPeriodSecs (Default Value): 600
router.multiTenant.transport.idleConnTimeoutSecs (Default Value): 5
router.multiTenant.transport.insecureSkipVerify (Default Value): true
router.probes.liveness.failOnLongFailingReadiness.enabled (Default Value): true
router.probes.liveness.failOnLongFailingReadiness.failureDurationSecs (Default Value): 60
router.profiling.enabled (Default Value): false
router.proxy.httpUrl (Default Value): 
router.proxy.httpsUrl (Default Value): 
router.proxy.ignoredHosts (Default Value): []
router.redirectUnknownPathToArtifactoryEnabled (Default Value): false
router.retry.enabled (Default Value): true
router.retry.enabledOnUnavailable (Default Value): true
router.security.cipherSuites (Default Value): TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
router.serviceRegistry.accessUrl (Applicative Resolution): http://localhost:8040/access
router.serviceRegistry.insecure (File): false
router.serviceRegistry.requestTimeout (Default Value): 15s
router.serviceRegistry.skipJoinConnectivityTest (Default Value): false
router.serviceRegistry.topologyServiceTokenExpirySecs (Default Value): 600
router.serviceRegistry.topologyUrl (Applicative Resolution): http://localhost:8040/access
router.serviceRegistry.useTopologyService (Default Value): false
router.supportBundle.aggregationTimeout (Default Value): 1h0m0s
router.topology.external.allowH2c (Default Value): true
router.topology.external.healthRequestTimeoutSecs (Default Value): 5
router.topology.external.protocolFinderCacheSecs (Default Value): 600
router.topology.external.refresh.interval (Default Value): 3s
router.topology.external.refresh.maxStaleHeartbeat (Default Value): 30s
router.topology.external.skipIpCheck (Default Value): false
router.topology.local.enableNodeStatusBroadcast (Default Value): true
router.topology.local.healthCheck.healthyThreshold (Default Value): 2
router.topology.local.healthCheck.interval (Default Value): 5s
router.topology.local.healthCheck.requestTimeout (Default Value): 5s
router.topology.local.healthCheck.unhealthyThreshold (Default Value): 2
router.topology.local.ignorePersistedServices (Default Value): false
router.topology.local.requiredServiceTypes (Environment Variable: JF_ROUTER_TOPOLOGY_LOCAL_REQUIREDSERVICETYPES): jfrt,jfac,jfob,jfmd,jfevt,jffe,jfcon
shared.database.driver (File): org.postgresql.Driver
shared.database.type (File): postgresql
shared.database.url (File): jdbc:postgresql://artifactory-postgresql:5432/artifactory
shared.database.username (File): artifactory
shared.extraJavaOpts (File): -Dartifactory.graceful.shutdown.max.request.duration.millis=30000 -Dartifactory.access.client.max.connections=50

shared.jfrogUrl (Default Value): 
shared.logging.consoleLog.enabled (File): false
shared.logging.consoleLog.format (Default Value): shared.logging.consoleLog.format
shared.logging.enableJsonConsoleLogAppenders (Default Value): false
shared.multiTenant.cellId (Default Value): 
shared.multiTenant.enabled (Default Value): false
shared.multiTenant.tenantRegistryClient.caCert (Default Value): 
shared.multiTenant.tenantRegistryClient.cacheExpirationSecs (Default Value): 21600
shared.multiTenant.tenantRegistryClient.clientCert (Default Value): 
shared.multiTenant.tenantRegistryClient.clientCertKey (Default Value): *****
shared.multiTenant.tenantRegistryClient.dialTimeoutSecs (Default Value): 10
shared.multiTenant.tenantRegistryClient.endpoints (Default Value): []
shared.multiTenant.tenantRegistryClient.requestTimeoutSecs (Default Value): 30
shared.newrelic.appName (Default Value): 
shared.newrelic.distributedTracerEnabled (Default Value): true
shared.newrelic.enableDebugLog (Default Value): false
shared.newrelic.enabled (Default Value): false
shared.newrelic.licenseKey (Default Value): *****
shared.node.id (Environment Variable: JF_SHARED_NODE_ID): artifactory-0
shared.node.ip (Environment Variable: JF_SHARED_NODE_IP): 10.128.2.43
shared.node.name (Environment Variable: JF_SHARED_NODE_NAME): artifactory-0
shared.node.port (Default Value): 0
shared.node.tlsEnabled (Default Value): false
shared.security.bootstrapKeysReadTimeoutSecs (Default Value): 300
shared.security.joinKeyFile (Default Value): etc/security/join.key
shared.security.masterKeyExternal (Default Value): false
shared.security.masterKeyFile (Default Value): etc/security/master.key
system.yaml (Environment Variable: JF_SYSTEM_YAML): /opt/jfrog/router/var/etc/system.yaml
topology.grpcPort (Default Value): 8021
topology.port (Default Value): 8020
2024-03-08T11:59:24.206Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 5 seconds with 5m0s timeout
2024-03-08T11:59:29.209Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 10 seconds with 5m0s timeout
2024-03-08T11:59:34.213Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 15 seconds with 5m0s timeout
2024-03-08T11:59:39.215Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 20 seconds with 5m0s timeout
2024-03-08T11:59:44.220Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 25 seconds with 5m0s timeout
2024-03-08T11:59:49.224Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 30 seconds with 5m0s timeout
2024-03-08T11:59:54.227Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 35 seconds with 5m0s timeout
2024-03-08T11:59:59.230Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 40 seconds with 5m0s timeout
2024-03-08T12:00:04.234Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 45 seconds with 5m0s timeout
2024-03-08T12:00:09.253Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 50 seconds with 5m0s timeout
2024-03-08T12:00:14.258Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 55 seconds with 5m0s timeout
2024-03-08T12:00:19.263Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 60 seconds with 5m0s timeout
2024-03-08T12:00:24.267Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 65 seconds with 5m0s timeout
2024-03-08T12:00:29.270Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 70 seconds with 5m0s timeout
2024-03-08T12:00:34.274Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 75 seconds with 5m0s timeout
2024-03-08T12:00:39.277Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 80 seconds with 5m0s timeout
2024-03-08T12:00:44.280Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 85 seconds with 5m0s timeout
2024-03-08T12:00:49.284Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 90 seconds with 5m0s timeout
2024-03-08T12:00:54.287Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 95 seconds with 5m0s timeout
2024-03-08T12:00:59.292Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 100 seconds with 5m0s timeout
2024-03-08T12:01:04.295Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 105 seconds with 5m0s timeout
2024-03-08T12:01:09.298Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 110 seconds with 5m0s timeout
2024-03-08T12:01:14.302Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 115 seconds with 5m0s timeout
2024-03-08T12:01:19.304Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 120 seconds with 5m0s timeout
2024-03-08T12:01:24.307Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 125 seconds with 5m0s timeout
2024-03-08T12:01:29.312Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 130 seconds with 5m0s timeout
2024-03-08T12:01:34.316Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 135 seconds with 5m0s timeout
2024-03-08T12:01:39.320Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 140 seconds with 5m0s timeout
2024-03-08T12:01:44.324Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 145 seconds with 5m0s timeout
2024-03-08T12:01:49.328Z [36m[jfrou][0m [34m[INFO ][0m [6c11dd5ef278b11f] [security_keys.go:185          ] [main                ] [] - Cluster join: Join key is missing. Pending for 150 seconds with 5m0s timeout
Terminate signal received, attempting a graceful shutdown (264)

**Comment by jnimmy** [comment]
I was installing on openshift..could you please help here..as am not able to move

**Comment by giangnd1999** [comment]
Đã có thằng nào fix đc chưa nhỉ, đm tự nhiên tao lại bị

**Comment by artm** [comment]
same as https://github.com/jfrog/charts/issues/1917
