### ISSUE TITLE
Artifactory HA Google Storage requires identity

### ISSUE THREAD

**Issue by flaper87** [jfrog/charts#1312]
**Is this a request for help?**:

Is there a way to only use the service account when using `google-storage`?

If not, is there a way to set the `indentity` and `credential` keys using a secret?

https://github.com/jfrog/charts/blob/cc5e9667b9b12f95a154e1afd608429758a9ff21/stable/artifactory-ha/values.yaml#L1009-L1036

Artifactory fails to start if I leave the `identity` and `credential` fields empty. Same thing if I put random values. I have confirmed that the service account credentials exist in the deployment and that they are correct.

I'm using the artifactory-ha chart

**Comment by rahulsadanandan** [comment]
@flaper87 Thanks for reporting this. This seems to be a bug, I was able to reproduce the issue. We have created a ticket internally and working on it.
Will update you soon.
cc @chukka

**Comment by ChocPanda** [comment]
Hey @rahulsadanandan, has this issue been resolved? I am currently unable to get Artifactory deployed at all with a Google Cloud Storage backend. I currently have the following exception

```Caused by: java.lang.RuntimeException: Missing identity field in config                                                                                                                                        │
│ artifactory     at org.artifactory.addon.filestore.type.jets3t.gcs.GoogleJets3tBinaryProvider.setCredentials(GoogleJets3tBinaryProvider.java:313)                                                                          │
│ artifactory     at org.artifactory.addon.filestore.type.jets3t.gcs.GoogleJets3tBinaryProvider.initialize(GoogleJets3tBinaryProvider.java:100)                                                                              │
│ artifactory     at org.jfrog.storage.binstore.providers.builder.BinaryProviderFactory.build(BinaryProviderFactory.java:104)                                                                                                │
│ artifactory     at org.jfrog.storage.binstore.providers.builder.BinaryProviderFactory.build(BinaryProviderFactory.java:92)                                                                                                 │
│ artifactory     at org.jfrog.storage.binstore.providers.builder.BinaryProviderFactory.build(BinaryProviderFactory.java:92)                                                                                                 │
│ artifactory     at org.jfrog.storage.binstore.providers.builder.BinaryProviderFactory.build(BinaryProviderFactory.java:92)                                                                                                 │
│ artifactory     at org.jfrog.storage.binstore.providers.builder.BinaryProviderFactory.build(BinaryProviderFactory.java:92)                                                                                                 │
│ artifactory     at org.jfrog.storage.binstore.providers.builder.BinaryProviderFactory.buildProviders(BinaryProviderFactory.java:81)                                                                                        │
│ artifactory     at org.jfrog.storage.binstore.manager.BinaryProviderManagerImpl.<init>(BinaryProviderManagerImpl.java:147)                                                                                                 │
│ artifactory     at org.artifactory.storage.db.binstore.service.BinaryServiceImpl.initialize(BinaryServiceImpl.java:274)                                                                                                    │
│ artifactory     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                                          │
│ artifactory     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                                        │
│ artifactory     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                                │
│ artifactory     at java.base/java.lang.reflect.Method.invoke(Method.java:566)                                                                                                                                              │
│ artifactory     at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)                                            │
│ artifactory     at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)                                │
│ artifactory     at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
```
