### ISSUE TITLE
artifactory-oss don't start 

### ISSUE THREAD

**Issue by Weigle** [jfrog/charts#1421]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
helm version: {Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
kubernates version: 1.17.17-gke.3000

**Which chart**:
4.0.0

**What happened**:
artifactory-oss never stay running 

if see the log. The aplication show this error
```
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.artifactory.lifecycle.webapp.servlet.ArtifactoryContextConfigListener.configure(ArtifactoryContextConfigListener.java:270)
	at org.artifactory.lifecycle.webapp.servlet.ArtifactoryContextConfigListener$1.run(ArtifactoryContextConfigListener.java:124)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'binaryServiceImpl': Invocation of init method failed; nested exception is java.lang.RuntimeException: Failed to initiate binary provider.
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:415)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
	at org.artifactory.spring.ArtifactoryApplicationContext.refresh(ArtifactoryApplicationContext.java:274)
	at org.artifactory.spring.ArtifactoryApplicationContext.<init>(ArtifactoryApplicationContext.java:174)
	... 6 common frames omitted
Caused by: java.lang.RuntimeException: Failed to initiate binary provider.
	at org.jfrog.storage.binstore.providers.builder.BinaryProviderFactory.create(BinaryProviderFactory.java:73)
	at org.jfrog.storage.binstore.providers.builder.BinaryProviderFactory.build(BinaryProviderFactory.java:90)
	at org.jfrog.storage.binstore.providers.builder.BinaryProviderFactory.build(BinaryProviderFactory.java:92)
	at org.jfrog.storage.binstore.providers.builder.BinaryProviderFactory.buildProviders(BinaryProviderFactory.java:81)
	at org.jfrog.storage.binstore.manager.BinaryProviderManagerImpl.<init>(BinaryProviderManagerImpl.java:154)
	at org.artifactory.storage.db.binstore.service.BinaryServiceImpl.initialize(BinaryServiceImpl.java:231)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 19 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.jfrog.storage.binstore.providers.builder.BinaryProviderFactory.create(BinaryProviderFactory.java:61)
	... 31 common frames omitted
```

**What you expected to happen**:

the artifactory-oss start application
**How to reproduce it** (as minimally and precisely as possible):

run the script with the values 
```sh
helm install artifactory-oss -f artifactory-oss/values.yaml jfrog/artifactory-oss --debug  --version 4.0.0
```
```yaml
artifactory:
  artifactory:

    image:
      registry: releases-docker.jfrog.io
      repository: jfrog/artifactory-oss

    resources: {}

    javaOpts: {}




    admin:
      ip: "localhost" 
      username: "XXXXXXX"
      password: "XXXXXXX^"



  installer:
    platform: art-oss-helm

  nginx:
    enabled: false
    service:
      type: LoadBalancer


  ingress:
    enabled: false
    tls:

  postgresql:
    enabled: false

  databaseUpgradeReady: "yes"


  database:
    type: postgresql
    driver: org.postgresql.Driver
    ## If you set the url, leave host and port empty
    url: jdbc:postgresql://XXXXXX:5432/artifactory
    user: XXXXXXX
    password: XXXXXXX
    secrets: {}


## Enable the PostgreSQL sub chart
postgresql:
  enabled: false


```

**Comment by Weigle** [comment]
hi, i found this issue https://github.com/jfrog/charts/issues/961
and resolved my problem.
