### ISSUE TITLE
Artifactory logs "Error: ENOENT: no such file or directory, mkdir '/opt/jfrog/artifactory/data/frontend/usage'     at Object.mkdirSync (fs.js:757:3)" every minute

### ISSUE THREAD

**Issue by jlentzfl** [jfrog/charts#1576]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:  Helm v3.5.2, Kubernetes 1.20.10-gke.1600

**Which chart**: jfrog-platform 10.1.2

**What happened**: 
There are 2 replicas of artifactory running and in each of them there are logs every minute as shown below:

2022-01-26T21:51:30.237Z [jffe ] [ERROR] [                ] [                              ] [main                ] - Error: ENOENT: no such file or directory, mkdir '/opt/jfrog/artifactory/data/frontend/usage'
    at Object.mkdirSync (fs.js:757:3)
    at File._createLogDirIfNotExist (/opt/jfrog/artifactory/app/frontend/bin-1.30.1/server/dist/node_modules/winston/lib/winston/transports/file.js:691:10)
    at new File (/opt/jfrog/artifactory/app/frontend/bin-1.30.1/server/dist/node_modules/winston/lib/winston/transports/file.js:92:28)
    at LoggerOptionsFactory.getLogFileTransport (/opt/jfrog/artifactory/app/frontend/bin-1.30.1/server/dist/node_modules/@jfrog/nodejs-commons/src/logger/LoggerOptionsFactory.ts:51:10)
    at LoggerOptionsFactory.get (/opt/jfrog/artifactory/app/frontend/bin-1.30.1/server/dist/node_modules/@jfrog/nodejs-commons/src/logger/LoggerOptionsFactory.ts:27:60)
    at LoggerManager._createLogger (/opt/jfrog/artifactory/app/frontend/bin-1.30.1/server/dist/node_modules/@jfrog/nodejs-commons/src/logger/LoggerManager.ts:112:33)
    at LoggerManager._getLogger (/opt/jfrog/artifactory/app/frontend/bin-1.30.1/server/dist/node_modules/@jfrog/nodejs-commons/src/logger/LoggerManager.ts:102:22)
    at LoggerManager.getLoggerById (/opt/jfrog/artifactory/app/frontend/bin-1.30.1/server/dist/node_modules/@jfrog/nodejs-commons/src/logger/LoggerManager.ts:55:15)
    at Function.getLogger (/opt/jfrog/artifactory/app/frontend/bin-1.30.1/server/dist/node_modules/@jfrog/nodejs-commons/src/metric-framework/services/FeatureAdoptionLogger.ts:24:17)
    at MetricsHelper.start (/opt/jfrog/artifactory/app/frontend/bin-1.30.1/server/dist/node_modules/@jfrog/nodejs-commons/src/metric-framework/MetricsHelper.ts:29:51)

I believe jffe stands for jfrog frontend.  The artifactory subchart's values.yaml does not have any loggers enabled so it's puzzling why this is happening.
**What you expected to happen**:  Logs to be free of mkdir '/opt/jfrog/artifactory/data/frontend/usage failure messages.

**How to reproduce it** (as minimally and precisely as possible):  We have an Enterprise X license with values.yaml including
distribution:
  enabled: false
pipelines:
  enabled: false
redis:
  enabled: false
insight:
  enabled: false

**Anything else we need to know**:  Thanks in advance for your help!

**Comment by amithins** [comment]
This does not look like an issue specific to helm. Since you have an Enterprise plus license, you are entitled to support. [Please open a ticket and link](https://jfrog.com/support/) this issue there.

**Comment by jlentzfl** [comment]
Thank you @amithins .  I have done so.  Support responded that the newer 7.31.x versions have fixed this issue which seem to be the case.
