### ISSUE TITLE
org.artifactory.addon.ha.ClusterOperationsService

### ISSUE THREAD

**Issue by RamyHuang** [jfrog/charts#1746]
2023-04-14T01:52:49.878Z [jfrt ] [ERROR] [                ] [actoryHeartbeatServiceImpl:242] [hbScheduler_Worker-4] - Failed to update Binary store about cluster changes
java.lang.RuntimeException: Could not find bean of type 'org.artifactory.addon.ha.ClusterOperationsService'.
	at org.artifactory.spring.ArtifactoryApplicationContext.beanForType(ArtifactoryApplicationContext.java:621)
	at org.artifactory.storage.db.servers.service.ArtifactoryHeartbeatServiceImpl$HeartbeatJob.updateBinaryServiceClusterChanges(ArtifactoryHeartbeatServiceImpl.java:239)
	at org.artifactory.storage.db.servers.service.ArtifactoryHeartbeatServiceImpl$HeartbeatJob.onExecute(ArtifactoryHeartbeatServiceImpl.java:219)
	at org.artifactory.schedule.QuartzCommand.doExecute(QuartzCommand.java:76)
	at org.artifactory.schedule.QuartzCommand.execute(QuartzCommand.java:57)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2023/04/14 01:52:52 DEBUG  On permissions affected - received message: type:KEEP_ALIVE

**Comment by Logeshwarsn** [comment]
@RamyHuang Can you please provide more information like chart version that you are using and reproducible steps ? Please use github templates while raising an issue going forward.
