### ISSUE TITLE
JFrog artifactory is unhealthy

### ISSUE THREAD

**Issue by myedla1** [jfrog/charts#1909]
Hi Team,
We are experiencing issues with Artifactory in our cluster, which is currently marked as Unhealthy. Recently, we adjusted the replica count to 0 and then restored it. Since making these changes, we have started encountering these problems.

Could you please assist us with this issue?

===========================
Exception in thread "grpc-nio-worker-ELG-1-1" Exception in thread "grpc-nio-worker-ELG-1-8" java.lang.NoClassDefFoundError: io/netty/buffer/PoolArena$1 at io.netty.buffer.PoolArena.freeChunk(PoolArena.java:247) at io.netty.buffer.PoolThreadCache$MemoryRegionCache.freeEntry(PoolThreadCache.java:430) at io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:396) at io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:388) at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:254) at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:245) at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:218) at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:533) at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:500) at io.netty.util.concurrent.FastThreadLocal.remove(FastThreadLocal.java:257) at io.netty.util.concurrent.FastThreadLocal.removeAll(FastThreadLocal.java:67) at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1039) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.base/java.lang.Thread.run(Thread.java:829) java.lang.NoClassDefFoundError: io/netty/buffer/PoolArena$1 at io.netty.buffer.PoolArena.freeChunk(PoolArena.java:247) at io.netty.buffer.PoolThreadCache$MemoryRegionCache.freeEntry(PoolThreadCache.java:430) at io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:396) at io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:388) at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:254) at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:245) at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:218) at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:533) at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:500) at io.netty.util.concurrent.FastThreadLocal.remove(FastThreadLocal.java:257) at io.netty.util.concurrent.FastThreadLocal.removeAll(FastThreadLocal.java:67) at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1039) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.base/java.lang.Thread.run(Thread.java:829) Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [io.netty.buffer.PoolArena$1]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access. at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1425) at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1262)
===========================

Thanks & Regards,
Madhu

**Comment by gitta-jfrog** [comment]
Hello @myedla1 

Thank you for reaching out. 
If you are having support as part of your JFrog subscription - please open support ticket and our support engineers will work with you up to resolution.

if you are not having support - I'll ask you to share more details on your Artifactory deployment (chart version, application version, database type, recent upgrades, your values yaml ) and we will try to assist as much as we can.

Thanks!
