### ISSUE TITLE
Networkpolicy creation should be optional.

### ISSUE THREAD

**Issue by Infinityxx** [jfrog/charts#524]
**Is this a request for help?**: No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

**Which chart**: artifactory-ha

**What happened**: The helm chart tries to creates/change the networkpolicy

helm install --name artifactory-ha jfrog/artifactory-ha --tiller-namespace mynamespace

Error: release artifactory-ha failed: networkpolicies.networking.k8s.io is forbidden: User "system:serviceaccount:mynamespace:default" cannot create resource "networkpolicies" in API group "networking.k8s.io" in the namespace "default"  

**What you expected to happen**: Some customers have their own networkpolicy and restricted from being able to change them.
We should check if there is already a networkpolicy is enabled, and not attempt to change it, when a user provides his namespace.

Creating a new service account is not always possible.

**Comment by danielezer** [comment]
@Infinityxx You can achieve this be setting the following in your values file:
```
networkpolicy: []
```

This will make sure that the network policy will not be created. 
I can't really change this inherently because I don't want to break compatibility for current users.

**Comment by yiwu1** [comment]
@danielezer Thanks for your reply. I changed accordingly in my forked repo per your instruction, how to publish the new chart so that I can install new chart like following commands?
helm repo add jfrog https://charts.jfrog.io
helm install --name artifactory-ha jfrog/artifactory-ha

**Comment by danielezer** [comment]
@yiwu1 i think we have a misunderstanding. You don’t need to fork the repo, you can do that with our chart by providing custom values to the chart installation.
This is how you would do that:

1. Create a values file by the name values.yaml with the following content:

networkPolicy: []

2. Install the chart using this values file:
helm install —name artifactory jfrog/artifactory —values values.yaml

**Comment by yiwu1** [comment]
@danielezer Could you please suggest further?
$ cat values.yaml
networkPolicy: []
$ helm install --name artifactory-ha jfrog/artifactory-ha --tiller-namespace yiwu1-ns --values values.yaml
Error: release artifactory-ha failed: networkpolicies.networking.k8s.io is forbidden: User "system:serviceaccount:yiwu1-ns:default" cannot create resource "networkpolicies" in API group "networking.k8s.io" in the namespace "default"

**Comment by eldada** [comment]
@yiwu1 - seems like we do have an issue here. I'll reopen and work with @danielezer on this.
Can I ask you to download the chart locally, extract and remove the file `artifactory-networkpolicy.yaml`?
Then try deploying with the local extracted directory.
Let us know if it helps.

**Comment by yiwu1** [comment]
@eldada Thanks for your help, looks like networkpolicy step went through with remove **artifactory-networkpolicy.yaml** . But I am now currently blocked by "**poddisruptionbudgets**" resource, is it possible to remove that?
yiwu1@npm-test-3173903:~/JFrog$ ls -ltr
total 60
-rwxr-xr-x 1 yiwu1 nogroup   807 Oct  7 00:55 artifactory-networkpolicy.yaml
-rw-r--r-- 1 yiwu1 nogroup 50991 Oct  7 00:55 artifactory-ha-0.17.0.tgz
drwxr-xr-x 5 yiwu1 nogroup  4096 Dec  2 18:41 artifactory-ha
yiwu1@npm-test-3173903:~/JFrog$ helm install --name artifactory-ha ./artifactory-ha --tiller-namespace yiwu1-ns
Error: release artifactory-ha failed: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:yiwu1-ns:default" cannot create resource "poddisruptionbudgets" in API group "policy" in the namespace "default"

**Comment by eldada** [comment]
I think you are running with very restricted permissions on your cluster.
You can try removing the file `artifactory-node-pdb.yaml` and try again. We might need to make it optional too.

**Comment by yiwu1** [comment]
@eldada I should have permission on my namespace as I given the namespace name explicitly. Removed **artifactory-node-pdb.yaml** and get other error again:

_~/JFrog$ helm install --name artifactory-ha ./artifactory-ha --tiller-namespace yiwu1-ns
Error: release artifactory-ha failed: secrets is forbidden: User "system:serviceaccount:yiwu1-ns:default" cannot create resource "secrets" in API group "" in the namespace "default"_

Even I remove **artifactory-secrets.yaml** here, it still gets blocked, any idear why it always create resource in default namespace ? Any walk around to bypass the part?Thanks!

**Comment by danielezer** [comment]
@yiwu1 You provide the `tiller-namespace`, you need to provide `namespace` as well. There is a different between `tiller-namespace` which is the namespace tiller is installed in, to `namespace` which is the namespace you install your chart in.

**Comment by danielezer** [comment]
@yiwu1 Please let me know if this fixes your issue

**Comment by yiwu1** [comment]
@danielezer Thank you. I am able to deploy to my namespace but with **FAILED** status:
$ helm list --failed --tiller-namespace=yiwu1-ns
NAME          	REVISION	UPDATED                 	STATUS	CHART                	APP VERSION	NAMESPACE
artifactory-ha	1       	Sun Dec  8 20:11:14 2019	FAILED	artifactory-ha-0.17.0	6.13.0     	yiwu1-ns

**Comment by danielezer** [comment]
@yiwu1 That's progress :) 
Can you please share the output of you helm install command as well as the output of: 
`kubectl get pods -n yiwu1-ns ` ?

**Comment by yiwu1** [comment]
@danielezer I figured out my RBAC problem then chart can be deployed , the command using is exactly the same you given above.
kubectl get pods -n yiwu1-ns
NAME                                          READY   STATUS      RESTARTS   AGE
tiller-deploy-59d8697c85-gzbxk                1/1     Running     0          3h29m

**Comment by danielezer** [comment]
@yiwu1 so it seems that the pods never get created. Please try to delete the installation using `helm delete --purge artifactory-ha`

and then try to re-install the chart with the command I posted before. Let me know if it works

**Comment by yiwu1** [comment]
@danielezer It is successfully deployed but still no pods running, is there anything wrong here?
$ helm ls --all --tiller-namespace=yiwu1-ns
NAME          	REVISION	UPDATED                 	STATUS  	CHART               	APP VERSION	NAMESPACE
artifactory-ha	1       	Mon Dec  9 22:13:31 2019	DEPLOYED	artifactory-ha-1.3.0	6.16.0     	yiwu1-ns
 tess kubectl get pods --namespace yiwu1-ns
NAME                                          READY   STATUS      RESTARTS   AGE
tiller-deploy-59d8697c85-7gbw8                1/1     Running     0          152m

**Comment by eldada** [comment]
I suspect there is an error with the statefulsets. Can you get them and describe them:
```
$ kubectl get sts -n yiwu1-ns
...
$ kubectl describe sts -n yiwu1-ns <STS_NAME>
```

**Comment by yiwu1** [comment]
@eldada Due to restriction here, I had to remove all the subpath entry which defined here for example https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/templates/artifactory-node-statefulset.yaml#L327, is subpath must here?
LAST SEEN   TYPE      REASON                 KIND                    MESSAGE
17s         Warning   FailedCreate           StatefulSet             create Pod artifactory-ha-artifactory-ha-member-0 in StatefulSet artifactory-ha-artifactory-ha-member failed error: Pod "artifactory-ha-artifactory-ha-member-0" is invalid: spec.containers[0].volumeMounts.subPath: Forbidden: subPath is disabled by feature-gate
17s         Warning   FailedCreate           StatefulSet             create Pod artifactory-ha-artifactory-ha-primary-0 in StatefulSet artifactory-ha-artifactory-ha-primary failed error: Pod "artifactory-ha-artifactory-ha-primary-0" is invalid: spec.containers[0].volumeMounts.subPath: Forbidden: subPath is disabled by feature-gate

**Comment by eldada** [comment]
Yes. `subPath` is required in most cases or else you might mask other files needed in that same directory.

**Comment by yiwu1** [comment]
@eldada subPath was forbidden in our cluster for now, can I change as following for temp replacement:
From:
        - name: binarystore-xml
          mountPath: "/artifactory_extra_conf/binarystore.xml"
          subPath: binarystore.xml

To:
          - name: binarystore-xml
          mountPath: "/artifactory_extra_conf/"

**Comment by eldada** [comment]
Technically it is possible. But any other mounts to `/artifactory_extra_conf/` will be lost, as this is a whole directory mount.

**Comment by yiwu1** [comment]
@eldada After above change, application failed to start due to following error, any idea for the fix?Thanks!
dServiceImpl': Unsatisfied dependency expressed through method 'setBinaryService' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'binaryServiceImpl': Invocation of init method failed; nested exception is java.lang.RuntimeException: Failed to initialize binary providers. Reason IO exception occurred during the config read process
2019-12-13 07:38:41,195 [art-init] [ERROR] (o.a.w.s.ArtifactoryContextConfigListener:96) - Application could not be initialized: /opt/jfrog/artifactory/etc/binarystore.xml (Is a directory)
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

**Comment by eldada** [comment]
`/opt/jfrog/artifactory/etc/binarystore.xml (Is a directory)` is the reason. It should be a file, not a directory. Check your configuration.

**Comment by JfrogPrasanna** [comment]
closing due to no activity.
