### ISSUE TITLE
Distribution does not come up with default distribution chart due to invalid redis password

### ISSUE THREAD

**Issue by joonfrog** [jfrog/charts#59]
2018-09-28 18:01:15,926 [main] [WARN ] (c.j.b.d.c.DistributorApplicationContext:551) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'foremanDistributorService': Invocation of init method failed; nested exception is redis.clients.jedis.exceptions.JedisDataException: ERR invalid password
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'foremanDistributorService': Invocation of init method failed; nested exception is redis.clients.jedis.exceptions.JedisDataException: ERR invalid password
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:137)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at com.jfrog.bintray.distribution.context.DistributorApplicationContext.create(DistributorApplicationContext.java:39)
	at com.jfrog.bintray.distributor.DistributorRunner.<init>(DistributorRunner.java:30)
	at com.jfrog.bintray.distributor.DistributorRunner.main(DistributorRunner.java:36)
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR invalid password

The password for redis is randomly generated and distribution service does not correctly configure itself to use randomly generated password

**Comment by eldada** [comment]
@joonfrog - Can you please share the exact command line? Did you use the latest chart version (1.0.1)?

**Comment by joonfrog** [comment]
> @joonfrog - Can you please share the exact command line? Did you use the latest chart version (1.0.1)?

I am using the latest from our github. 

command:
helm install --name distribution jfrog/distribution

**Comment by eldada** [comment]
A fix to the mongodb error is in https://github.com/jfrog/charts/pull/68. I did not manage to reproduce an error with Redis. Can you test once PR is merged?

**Comment by eldada** [comment]
@joonfrog - please check now with distribution-1.0.4.
