### ISSUE TITLE
azure blockBlobStorage as persistence on 9.0.23 

### ISSUE THREAD

**Issue by mrafieee** [jfrog/charts#675]
I fresh installed version 7.2.1 with chart 9.0.23.

It runs super slow and when trying to push artifacts it returns:

```
2020-03-13T22:31:01.880Z [jfrt ] [ERROR] [ab356a8766ac0e12] [ntuallyPersistedAddFileTask:89] [al-binary-provider-3] - Fail to persist 'add file' '/opt/jfrog/artifactory/var/data/artifactory/eventual/_add/83/83e43a68b15f335c33f74384873c983842da49c6'
2020-03-13T22:31:01.885Z [jfrt ] [ERROR] [ab356a8766ac0e12] [eBlobStorageBinaryProvider:225] [al-binary-provider-3] - Failed to upload blob to Azure Blob Storage
2020-03-13T22:31:01.885Z [jfrt ] [WARN ] [ab356a8766ac0e12] [.s.b.p.RetryBinaryProvider:157] [al-binary-provider-3] - Failed to add blob to next binary provider for the '1' time, a retry will start in seconds
2020-03-13T22:31:01.938Z [jfrt ] [ERROR] [ab356a8766ac0e12] [eBlobStorageBinaryProvider:225] [al-binary-provider-1] - Failed to upload blob to Azure Blob Storage
2020-03-13T22:31:01.939Z [jfrt ] [WARN ] [ab356a8766ac0e12] [.s.b.p.RetryBinaryProvider:157] [al-binary-provider-1] - Failed to add blob to next binary provider for the '2' time, a retry will start in seconds
2020-03-13T22:31:06.594Z [jfrt ] [ERROR] [ab356a8766ac0e12] [eBlobStorageBinaryProvider:225] [al-binary-provider-0] - Failed to upload blob to Azure Blob Storage
2020-03-13T22:31:06.594Z [jfrt ] [WARN ] [ab356a8766ac0e12] [.s.b.p.RetryBinaryProvider:157] [al-binary-provider-0] - Failed to add blob to next binary provider for the '3' time, a retry will start in seconds
2020-03-13T22:31:06.620Z [jfrt ] [ERROR] [ab356a8766ac0e12] [eBlobStorageBinaryProvider:225] [al-binary-provider-2] - Failed to upload blob to Azure Blob Storage
2020-03-13T22:31:06.620Z [jfrt ] [WARN ] [ab356a8766ac0e12] [.s.b.p.RetryBinaryProvider:157] [al-binary-provider-2] - Failed to add blob to next binary provider for the '3' time, a retry will start in seconds
2020-03-13T22:31:06.680Z [jfrt ] [ERROR] [ab356a8766ac0e12] [eBlobStorageBinaryProvider:225] [al-binary-provider-4] - Failed to upload blob to Azure Blob Storage
2020-03-13T22:31:06.680Z [jfrt ] [ERROR] [ab356a8766ac0e12] [.s.b.p.RetryBinaryProvider:164] [al-binary-provider-4] - Failed to add blob to next binary provider
java.lang.RuntimeException: Failed to upload blob to Azure Blob Storage
    at org.artifactory.addon.filestore.type.azureblobstorage.AzureBlobStorageBinaryProvider.addSmallStream(AzureBlobStorageBinaryProvider.java:226)
    at org.artifactory.addon.filestore.type.azureblobstorage.AzureBlobStorageBinaryProvider.addStream(AzureBlobStorageBinaryProvider.java:198)
    at org.jfrog.storage.binstore.providers.RetryBinaryProvider.addStream(RetryBinaryProvider.java:154)
    at org.jfrog.storage.binstore.providers.RetryBinaryProvider.addStream(RetryBinaryProvider.java:162)
    at org.jfrog.storage.binstore.providers.RetryBinaryProvider.addStream(RetryBinaryProvider.java:162)
    at org.jfrog.storage.binstore.providers.RetryBinaryProvider.addStream(RetryBinaryProvider.java:162)
    at org.jfrog.storage.binstore.providers.RetryBinaryProvider.addStream(RetryBinaryProvider.java:162)
    at org.jfrog.storage.binstore.providers.RetryBinaryProvider.addStream(RetryBinaryProvider.java:162)
    at org.jfrog.storage.binstore.providers.RetryBinaryProvider.addStream(RetryBinaryProvider.java:69)
    at org.artifactory.addon.filestore.eventual.task.EventuallyPersistedAddFileTask.run(EventuallyPersistedAddFileTask.java:71)
    at org.artifactory.opentracing.TraceableRunnableDecorator.run(TraceableRunnableDecorator.java:25)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.microsoft.azure.storage.StorageException: The resource doesn't support specified Http Verb.
    at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87)
    at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:305)
    at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:196)
    at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadFullBlob(CloudBlockBlob.java:1035)
    at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:864)
    at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:743)
    at org.artifactory.addon.filestore.type.azureblobstorage.AzureBlobStorageBinaryProvider.addSmallStream(AzureBlobStorageBinaryProvider.java:221)
    ... 15 common frames omitted

**Comment by eldada** [comment]
@mrafieee  - can you share your generated config that's produced by 
```
helm get <release>
```
I'm mostly interested to see the resources and the generated `artifactory.persistence.binarystoreXml`.

**Comment by mrafieee** [comment]
@eldada 

```
<!-- Azure Blob Storage -->
<config version="2">
    <chain> <!--template="azure-blob-storage"-->
        <provider id="cache-fs" type="cache-fs">
            <provider id="eventual" type="eventual">
                <provider id="retry-azure-blob-storage" type="retry">
                    <provider id="azure-blob-storage" type="azure-blob-storage"/>
                </provider>
            </provider>
        </provider>
    </chain>

    <!-- Set max cache-fs size -->
    <provider id="cache-fs" type="cache-fs">
        <maxCacheSize>5e+10</maxCacheSize>
        <cacheProviderDir>cache</cacheProviderDir>
    </provider>

    <provider id="azure-blob-storage" type="azure-blob-storage">
        <accountName>yyyyy</accountName>
        <accountKey>xxxxx</accountKey>
        <endpoint>https://yyyyy.z9.web.core.windows.net/</endpoint>
        <containerName>artifactory</containerName>
        <testConnection>false</testConnection>
    </provider>
</config>
```

**Comment by eldada** [comment]
Thx! What about the resources allocated to the containers? Can you share them too? You can also 
```
kubectl describe pod <artifactory-pod>
```

**Comment by mrafieee** [comment]
```
Name:           artifactory-artifactory-0
Namespace:      artifactory
Priority:       0
Node:           aks-aksdev-xxxxx/x.x.x.x
Start Time:     Sun, 15 Mar 2020 08:45:40 -0400
Labels:         app=artifactory
                chart=artifactory-9.0.23
                component=artifactory
                controller-revision-hash=artifactory-artifactory-55f6794f54
                heritage=Helm
                release=artifactory
                role=artifactory
                statefulset.kubernetes.io/pod-name=artifactory-artifactory-0
Annotations:    checksum/access-creds: e819b5a92c7e5eba937d577b26f0f8e2cd7caab312ff616e4049f2640019a734
                checksum/binarystore: 8ac807ba744e9c804a202fcd7b9805288f88d9b2fad990d31f3a503353aa8615
                checksum/systemyaml: 852871f09572fdf9be35ae46f5b0a2bd37e84a7f6ff935e099e2dcb4fd74f457
Status:         Running
IP:             x.x.x.x
IPs:            <none>
Controlled By:  StatefulSet/artifactory-artifactory
Init Containers:
  delete-db-properties:
    Container ID:  docker://e9d43a7561c74acc268335aaea5b9d180c026c0a39a3c4300e15a1ed5ab580cf
    Image:         alpine:3.10
    Image ID:      docker-pullable://alpine@sha256:7c3773f7bcc969f03f8f653910001d99a9d324b4b9caa008846ad2c3089f5a5f
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      rm -fv /var/opt/jfrog/artifactory/etc/db.properties
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sun, 15 Mar 2020 08:47:01 -0400
      Finished:     Sun, 15 Mar 2020 08:47:01 -0400
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/opt/jfrog/artifactory from artifactory-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from artifactory-artifactory-token-4w4kp (ro)
  remove-lost-found:
    Container ID:  docker://b85d1960febf05e89eb781304783051b179f85dc0361964a6a48f1edbdf20a7e
    Image:         alpine:3.10
    Image ID:      docker-pullable://alpine@sha256:7c3773f7bcc969f03f8f653910001d99a9d324b4b9caa008846ad2c3089f5a5f
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      rm -rfv /var/opt/jfrog/artifactory/lost+found /var/opt/jfrog/artifactory/data/.lock
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sun, 15 Mar 2020 08:47:02 -0400
      Finished:     Sun, 15 Mar 2020 08:47:02 -0400
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/opt/jfrog/artifactory from artifactory-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from artifactory-artifactory-token-4w4kp (ro)
  access-bootstrap-creds:
    Container ID:  docker://ec47ac0bf2c13f89af78aaafbd46362b3ebb773cd4b7d49c69d93d4eba82e1ce
    Image:         alpine:3.10
    Image ID:      docker-pullable://alpine@sha256:7c3773f7bcc969f03f8f653910001d99a9d324b4b9caa008846ad2c3089f5a5f
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      echo "Preparing custom Access bootstrap.creds"; mkdir -p /var/opt/jfrog/artifactory/access/etc; cp -Lrf /tmp/access/bootstrap.creds /var/opt/jfrog/artifactory/access/etc/bootstrap.creds; chmod 600 /var/opt/jfrog/artifactory/access/etc/bootstrap.creds;

    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sun, 15 Mar 2020 08:47:04 -0400
      Finished:     Sun, 15 Mar 2020 08:47:04 -0400
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /tmp/access/bootstrap.creds from access-bootstrap-creds (rw,path="bootstrap.creds")
      /var/opt/jfrog/artifactory from artifactory-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from artifactory-artifactory-token-4w4kp (ro)
  copy-system-yaml:
    Container ID:  docker://53b0d5bbdd27e0975a46bbcd0741f43f97c6122f6e7f552dfd5919a49e550237
    Image:         alpine:3.10
    Image ID:      docker-pullable://alpine@sha256:7c3773f7bcc969f03f8f653910001d99a9d324b4b9caa008846ad2c3089f5a5f
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      sleep 30; echo "Copy system.yaml to /var/opt/jfrog/artifactory/etc"; mkdir -p /var/opt/jfrog/artifactory/etc; mkdir -p /var/opt/jfrog/artifactory/etc/access/keys/trusted; cp -fv /tmp/etc/system.yaml /var/opt/jfrog/artifactory/etc/system.yaml; echo "Remove /var/opt/jfrog/artifactory/lost+found folder if exists"; rm -rfv /var/opt/jfrog/artifactory/lost+found; echo "Copy joinKey to /var/opt/jfrog/artifactory/bootstrap/access/etc/security"; rm -rfv /tmp/join.key; echo -n ${ARTIFACTORY_JOIN_KEY} > /tmp/join.key; mkdir -p /var/opt/jfrog/artifactory/bootstrap/access/etc/security; cp -fv /tmp/join.key /var/opt/jfrog/artifactory/bootstrap/access/etc/security;

    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sun, 15 Mar 2020 08:47:04 -0400
      Finished:     Sun, 15 Mar 2020 08:47:34 -0400
    Ready:          True
    Restart Count:  0
    Environment:
      ARTIFACTORY_JOIN_KEY:  <set to the key 'join-key' in secret 'artifactory-artifactory'>  Optional: false
    Mounts:
      /tmp/etc/system.yaml from systemyaml (rw,path="system.yaml")
      /var/opt/jfrog/artifactory from artifactory-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from artifactory-artifactory-token-4w4kp (ro)
  wait-for-db:
    Container ID:  docker://e006887abf8e80be1613f4517d896df60c2618c1c7911933d62f9101335434d1
    Image:         alpine:3.10
    Image ID:      docker-pullable://alpine@sha256:7c3773f7bcc969f03f8f653910001d99a9d324b4b9caa008846ad2c3089f5a5f
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      until nc -z -w 2 artifactory-postgresql 5432 && echo database ok; do
        sleep 2;
      done;

    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sun, 15 Mar 2020 08:47:36 -0400
      Finished:     Sun, 15 Mar 2020 08:47:36 -0400
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from artifactory-artifactory-token-4w4kp (ro)
  migration-artifactory:
    Container ID:  docker://47fdef05fb9dd10b346eb0eadcc5aca6e1e4a845b15ea8fd89b4e2f5fa3b5323
    Image:         docker.bintray.io/jfrog/artifactory-pro:7.2.1
    Image ID:      docker-pullable://docker.bintray.io/jfrog/artifactory-pro@sha256:9c6b58128f2db707f7592075b5c68a5b29a74ae0ebed5052d26a3f794dd3190b
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/bash
      -c
      scriptsPath="/opt/jfrog/artifactory/app/bin"; mkdir -p $scriptsPath; echo "Copy migration scripts and Run migration"; cp -fv /tmp/migrate.sh $scriptsPath/migrate.sh; cp -fv /tmp/migrationHelmInfo.yaml $scriptsPath/migrationHelmInfo.yaml; cp -fv /tmp/migrationStatus.sh $scriptsPath/migrationStatus.sh; mkdir -p /var/opt/jfrog/artifactory/log; bash $scriptsPath/migrationStatus.sh 7.2.1 > >(tee /var/opt/jfrog/artifactory/log/helm-migration.log) 2>&1;

    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sun, 15 Mar 2020 08:47:37 -0400
      Finished:     Sun, 15 Mar 2020 08:47:37 -0400
    Ready:          True
    Restart Count:  0
    Environment:
      JF_SHARED_DATABASE_PASSWORD:  <set to the key 'postgresql-password' in secret 'artifactory-postgresql'>  Optional: false
    Mounts:
      /artifactory_bootstrap/artifactory.lic from artifactory-license (rw,path="artifactory.lic")
      /artifactory_bootstrap/binarystore.xml from binarystore-xml (rw,path="binarystore.xml")
      /tmp/migrate.sh from migration-scripts (rw,path="migrate.sh")
      /tmp/migrationHelmInfo.yaml from migration-scripts (rw,path="migrationHelmInfo.yaml")
      /tmp/migrationStatus.sh from migration-scripts (rw,path="migrationStatus.sh")
      /var/opt/jfrog/artifactory from artifactory-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from artifactory-artifactory-token-4w4kp (ro)
Containers:
  artifactory:
    Container ID:  docker://591c0ec617b9c13d8963904a3373735c660a7f0e9c5fc173b20a9cef27ea3c34
    Image:         docker.bintray.io/jfrog/artifactory-pro:7.2.1
    Image ID:      docker-pullable://docker.bintray.io/jfrog/artifactory-pro@sha256:9c6b58128f2db707f7592075b5c68a5b29a74ae0ebed5052d26a3f794dd3190b
    Ports:         8082/TCP, 8081/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      /bin/sh
      -c
      set -e; if [ -d /artifactory_extra_conf ] && [ -d /artifactory_bootstrap ]; then
        echo "Copying bootstrap config from /artifactory_extra_conf to /artifactory_bootstrap";
        cp -Lrfv /artifactory_extra_conf/ /artifactory_bootstrap/;
      fi; /entrypoint-artifactory.sh

    State:          Running
      Started:      Sun, 15 Mar 2020 08:47:38 -0400
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     6
      memory:  8Gi
    Requests:
      cpu:      2
      memory:   4Gi
    Liveness:   http-get http://:8082/router/api/v1/system/health delay=180s timeout=10s period=10s #success=1 #failure=10
    Readiness:  http-get http://:8082/router/api/v1/system/health delay=60s timeout=10s period=10s #success=1 #failure=10
    Environment:
      JF_SHARED_DATABASE_PASSWORD:  <set to the key 'postgresql-password' in secret 'artifactory-postgresql'>  Optional: false
    Mounts:
      /artifactory_bootstrap/artifactory.lic from artifactory-license (rw,path="artifactory.lic")
      /artifactory_bootstrap/binarystore.xml from binarystore-xml (rw,path="binarystore.xml")
      /artifactory_bootstrap/info/installer-info.json from installer-info (rw,path="installer-info.json")
      /var/opt/jfrog/artifactory from artifactory-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from artifactory-artifactory-token-4w4kp (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  artifactory-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  artifactory-volume-artifactory-artifactory-0
    ReadOnly:   false
  binarystore-xml:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  artifactory-artifactory-binarystore
    Optional:    false
  migration-scripts:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      artifactory-artifactory-migration-scripts
    Optional:  false
  installer-info:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      artifactory-artifactory-installer-info
    Optional:  false
  artifactory-license:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  artifactory-artifactory-license
    Optional:    false
  access-bootstrap-creds:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  artifactory-artifactory-bootstrap-creds
    Optional:    false
  systemyaml:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  artifactory-artifactory-systemyaml
    Optional:    false
  artifactory-artifactory-token-4w4kp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  artifactory-artifactory-token-4w4kp
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s

```

**Comment by eldada** [comment]
Looks like the resources are OK. 
As for the Azure binary store config, can you look into a couple of related errors:
1. https://stackoverflow.com/questions/44247379/unsupportedhttpverb-the-resource-doesnt-support-specified-http-verb-requesti

2. https://docs.microsoft.com/en-us/rest/api/storageservices/cross-origin-resource-sharing--cors--support-for-the-azure-storage-services

Seems like something is either a bad URL (although your settings seem fine), or permissions on the blob storage side.

**Comment by eldada** [comment]
@mrafieee - any progress here?

**Comment by mrafieee** [comment]
the issue is fixed, switched from `block blob storage` to `blob storage` the documentation on jfrog website is misleading https://www.jfrog.com/confluence/display/JFROG/Azure+Blob+Storage

**Comment by eldada** [comment]
Great!
Can you provide more details so we can take it back to our docs and improve?

**Comment by JfrogPrasanna** [comment]
@mrafieee Updated the link to allow users to create an  appropriate storage account. It could be a storage account using  blob containers, or block blob storage.
