### ISSUE TITLE
[ ARTIFACTORY ] - Ingress /api context not found

### ISSUE THREAD

**Issue by rdcarrera** [jfrog/charts#840]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): question/bug report?

**Version of Helm and Kubernetes**: 

**k8s**: Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
**helm**: Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

**Which chart**: 
artifactory:9.4.0

**What happened**:
api context doesn't work under an ingress

```
[root@b4c89b9f32fe assets]# ./jfrog rt config
Artifactory server ID: 0
JFrog Artifactory URL: https://artifactory.k8s.mydomain.com
JFrog Distribution URL (Optional): 
Access token (Leave blank for username and password/API key): 
[Error] Artifactory response: 404 Not Found
```
![image](https://user-images.githubusercontent.com/26046280/79905424-8bee0400-8416-11ea-913a-7362088408f5.png)

**How to reproduce it** (as minimally and precisely as possible):
Use the ingress configuration for enables Artifactory to work as a Docker Registry using the Repository Path method
```
ingress:
  enabled: true
  defaultBackend:
    enabled: false
  hosts:
  - artifactory.k8s.mydomain.com
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/proxy-read-timeout: "600"
    ingress.kubernetes.io/proxy-send-timeout: "600"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/(v2)/token /artifactory/api/docker/null/v2/token;
      rewrite ^/(v2)/([^\/]*)/(.*) /artifactory/api/docker/$2/$1/$3;
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  tls:
  - hosts:
    - artifactory.k8s.mydomain.com
```

**Anything else we need to know**:
The replication process of a docker repository also doesn't work and the error it's about the name resolution of the api host 
```
2020-04-21T19:23:57.924Z [jfrt ] [ERROR] [5e0986ca21d8485b] [o.a.a.c.BasicStatusHolder:211 ] [art-exec-2          ] - Error occurred while performing folder replication for 'docker-openshift:' to 'https://internalregistry': api: Temporary failure in name resolution
java.net.UnknownHostException: api: Temporary failure in name resolution
        at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at org.jfrog.client.http.CloseableHttpClientDecorator.doExecute(CloseableHttpClientDecorator.java:107)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.artifactory.repo.HttpRepo.doExecuteMethod(HttpRepo.java:500)
        at org.artifactory.repo.HttpRepo.doExecuteMethod(HttpRepo.java:493)
        at org.artifactory.repo.HttpRepo.executeMethod(HttpRepo.java:524)
        at org.artifactory.repo.HttpRepo.executeMethod(HttpRepo.java:464)
        at org.artifactory.addon.replication.core.context.RemoteRequestExecutor.executeMethod(RemoteRequestExecutor.java:38)
        at org.artifactory.addon.replication.core.context.server.TargetServerInfoResolver.executeRequestAndSetDetails(TargetServerInfoResolver.java:109)
        at org.artifactory.addon.replication.core.context.server.TargetServerInfoResolver.resolveTargetInfo(TargetServerInfoResolver.java:59)
        at org.artifactory.addon.replication.core.BaseReplicationProducer.resolveTargetInfo(BaseReplicationProducer.java:146)
        at org.artifactory.addon.replication.core.BaseReplicationProducer.init(BaseReplicationProducer.java:142)
        at org.artifactory.addon.replication.core.BaseReplicationProducer.run(BaseReplicationProducer.java:92)
        at org.artifactory.addon.replication.core.remote.RemoteReplicator.replicate(RemoteReplicator.java:59)
        at org.artifactory.addon.replication.core.remote.RemoteReplicator.replicate(RemoteReplicator.java:47)
        at org.artifactory.addon.replication.core.ReplicationAddonImpl.performRemoteReplication(ReplicationAddonImpl.java:119)
        at org.artifactory.repo.replication.RemoteReplicationJob.onExecute(RemoteReplicationJob.java:102)
        at org.artifactory.schedule.quartz.QuartzCommand.execute(QuartzCommand.java:48)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.artifactory.opentracing.TraceableRunnableDecorator.run(TraceableRunnableDecorator.java:30)
        at org.artifactory.concurrent.ArtifactoryRunnable.run(ArtifactoryRunnable.java:53)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

Thanks & Regards.

**Comment by chukka** [comment]
@rdcarrera  Thanks for reporting ! Just wondering is this a correct configuration 
`rewrite ^/(v2)/token /artifactory/api/docker/null/v2/token;`  **null**  value ? 

Also, can you share the output of `helm template ./chart` (with your above ingress  values)

**Comment by rdcarrera** [comment]
Hi @chukka 

About the ingress annotation, I copied from the README of the chart.

![image](https://user-images.githubusercontent.com/26046280/80188938-2d8d7500-8612-11ea-9e40-8433fca296df.png)


I added the next annotation trying to fix the problem:
-       rewrite ^/api/(.*) /artifactory/api/$1

After that, the jfrog client error it's different:

bash-4.4# jfrog rt config 
Artifactory server ID: 0
JFrog Artifactory URL: https://artifactory.mydomain.com
JFrog Distribution URL (Optional): 
Access token (Leave blank for username and password/API key): 
[Error] Artifactory response: 401 Unauthorized

But the replication still failing:

![image](https://user-images.githubusercontent.com/26046280/80190512-b9080580-8614-11ea-98bc-c74d404665bd.png)



About the chart values:

```
---
artifactory:
  masterKey: "hidden"
  joinKey: "hidden"
  persistence:
    existingClaim: 	artifactory-data
  license:
    licenseKey: |-
      hidden
  customInitContainers: |
    - name: "trust-ca-certificate"
      image: "rdcarrera/add-ca-to-cacert"
      imagePullPolicy: IfNotPresent
      env:
      - name: CACERT_DEST
        value: "/dest"
      - name: CERTS_FOLDER
        value: "/certs"
      volumeMounts:
      - name: artifactory-cacerts
        mountPath: /dest
      - name: mydomain-ca
        mountPath: /certs/mydomain.pem
        subPath: mydomain.pem
      - name: mydomain-ca
        mountPath: /certs/openshift.pem
        subPath: openshift.pem
      securityContext:
        privileged: true
        runAsUser: 0

  customVolumeMounts: |
    - name: artifactory-cacerts
      mountPath: "/opt/jfrog/artifactory/app/third-party/java/lib/security/cacerts"
      subPath: cacerts

  customVolumes: |
    - name: mydomain-ca
      configMap:
        name: mydomain-ca
    - name: artifactory-cacerts
      emptyDir: {}

nginx:
  enabled: false

ingress:
  enabled: true
  defaultBackend:
    enabled: false
  hosts:
  - artifactory.mydomain.com
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/proxy-read-timeout: "600"
    ingress.kubernetes.io/proxy-send-timeout: "600"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/(v2)/token /artifactory/api/docker/null/v2/token;
      rewrite ^/(v2)/([^\/]*)/(.*) /artifactory/api/docker/$2/$1/$3;
      rewrite ^/api/(.*) /artifactory/api/$1
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  tls:
  - hosts:
    - artifactory.mydomain.com

postgresql:
  postgresqlUsername: user
  postgresqlPassword: "hidden"
```

**Comment by Satheesh-Balachandran** [comment]
@rdcarrera Can  you try removing the new rewrite rule you added? and try with the "/artifactory" context? Like https://DOMAIN/artifactory/api/system/ping.

**Comment by rdcarrera** [comment]
Thanks @Satheesh-Balachandran !

I removed the the rule, I tested with the path and it works!

Also, when I tested with the rule my problem was when the cli ask for the access token I pass the API key, sorry.

**Access token** (Leave blank for username and password/API key): 

But I still with the same problem with the replication:

![image](https://user-images.githubusercontent.com/26046280/80467562-419ce380-893e-11ea-9416-775e9a592c1d.png)

How do you see this?, this is relative of the /api or I've to open a new issue?

Thanks & Regards.

**Comment by Satheesh-Balachandran** [comment]
> Thanks @Satheesh-Balachandran !
> 
> I removed the the rule, I tested with the path and it works!
> 
> Also, when I tested with the rule my problem was when the cli ask for the access token I pass the API key, sorry.
> 
> **Access token** (Leave blank for username and password/API key):
> 
> But I still with the same problem with the replication:
> 
> ![image](https://user-images.githubusercontent.com/26046280/80467562-419ce380-893e-11ea-9416-775e9a592c1d.png)
> 
> How do you see this?, this is relative of the /api or I've to open a new issue?
> 
> Thanks & Regards.

@rdcarrera Glad it worked. This seems to be a wrong configuration of the CLI. There is no context in the application with "/api". Issues here are more relevant to be related to any bug in the installation of the charts. Can you please open a support ticket with us to get answer for this behaviour?

**Comment by chukka** [comment]
Closing this issue
