### ISSUE TITLE
Detected failed migration to version 2 (Initial Schema Update)

### ISSUE THREAD

**Issue by rubensgomes** [jfrog/charts#884]
I am installing the latest 7. Artifactory OSS RPM version on CentOS using MySQL DB, and I keep getting following ERROR at startup in the access-service.log:

2020-05-07T01:00:07.584Z [jfac ] [INFO ] [abff6b19987ea600] [s.d.u.AccessJdbcHelperImpl:138] [ocalhost-startStop-2] - Database: MySQL 5.6.48. Driver: MySQL Connector/J mysql-connector-java-8.0.19 (Revision: a0ca826f5cdf51a98356fdfb1bf251eb042f80bf)
2020-05-07T01:00:07.584Z [jfac ] [INFO ] [abff6b19987ea600] [s.d.u.AccessJdbcHelperImpl:141] [ocalhost-startStop-2] - Connection URL: jdbc:mysql://localhost:3306/artdb?characterEncoding=UTF-8&elideSetAutoCommits=true&useSSL=false&serverTimezone=UTC
2020-05-07T01:00:15.164Z [jfac ] [ERROR] [abff6b19987ea600] [.s.d.u.AccessJdbcHelperImpl:66] [ocalhost-startStop-2] - Could not initialize database:
org.flywaydb.core.api.FlywayException: Detected failed migration to version 2 (Initial Schema Update)
        at org.flywaydb.core.internal.info.MigrationInfoImpl.validate(MigrationInfoImpl.java:218)
        at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.validate(MigrationInfoServiceImpl.java:327)
        at org.flywaydb.core.internal.command.DbValidate$2.call(DbValidate.java:174)
        at org.flywaydb.core.internal.command.DbValidate$2.call(DbValidate.java:164)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75)
        at org.flywaydb.core.internal.command.DbValidate.validate(DbValidate.java:164)

**Comment by shahiinn** [comment]
@rubensgomes : We handle any issues that comes as part of Jfrog installation charts here. We would recommend you to raise any other issues directly in [StackOverflow forum](https://stackoverflow.com/questions/tagged/artifactory?tab=Newest).
