### ISSUE TITLE
Artifactory HA google-storage configuration issue

### ISSUE THREAD

**Issue by w9n** [jfrog/charts#917]
**Is this a request for help?**:

---

 BUG REPORT

**Version of Helm and Kubernetes**:
helm:
```
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.7"}
```
k8s:
```
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.11", GitCommit:"fd078e6ed95d359cb2c9ca6561754806718c1c98", GitTreeState:"clean", BuildDate:"2020-04-13T20:10:31Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```
**Which chart**:
chart: artifactory-ha-2.4.10

**What happened**:
google storage provider does not load
```
kubectl logs artifactory-artifactory-ha-primary-0
....
2020-05-27T23:31:06.200Z [jfrt ] [INFO ] [5e2c6d9a67808b77] [GoogleJets3tBinaryProvider:320] [art-init            ] - Connecting to GCS endpoint: 'storage.googleapis.com'
2020-05-27T23:31:06.203Z [jfrt ] [INFO ] [5e2c6d9a67808b77] [.GoogleJets3tBinaryProvider:96] [art-init            ] - Bucket exists = false
2020-05-27T23:31:06.752Z [jfmd ] [INFO ] [5fe5a41034cc5f3a] [accessclient.go:51            ] [main                ] - Cluster join: Retry 20: Service registry ping failed, will retry. Error: Error while trying to connect to local router at address 'http://localhost:8046/access': Get http://localhost:8046/access/api/v1/system/ping: dial tcp 127.0.0.1:8046: connect: connection refused [access_client]
2020-05-27T23:31:07.183Z [jfrt ] [WARN ] [5e2c6d9a67808b77] [GoogleJets3tBinaryProvider:287] [art-init            ] - Failed to check if bucket exist, bucket artifactory-ha-gcp. Service Error Message.
2020-05-27T23:31:07.658Z [jfrt ] [ERROR] [5e2c6d9a67808b77] [GoogleJets3tBinaryProvider:211] [art-init            ] - Failed to put blob '83977ce3f81a6e8a00d39df2db3b21a8a7983bda' to GCS caused by 403:The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.
org.jets3t.service.ServiceException: Service Error Message.
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRequest(RestStorageService.java:409)
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRequest(RestStorageService.java:279)
```

**What you expected to happen**:
`Failed to check if bucket exist, bucket artifactory-ha-gcp. Service Error Message.`
`Bucket exists = false`
above error message indicates that belows config is not properly loaded.

**How to reproduce it** (as minimally and precisely as possible):
googlestorage values.yaml patch:
```
@@ -938,7 +980,20 @@ artifactory:
     googleStorage:
       ## When using GCP buckets as your binary store (Available with enterprise license only)
       gcpServiceAccount:
-        enabled: false
+        enabled: true
+        config: |
+          {
+             "type": "service_account",
..............
+          }
         ## Use either an existing secret prepared in advance or put the config (replace the content) in the values
         ## ref: https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/README.md#google-storage
         # customSecretName:
@@ -958,11 +1013,11 @@ artifactory:
       endpoint: storage.googleapis.com
       httpsOnly: false
       # Set a unique bucket name
-      bucketName: "artifactory-ha-gcp"
-      identity:
-      credential:
+      bucketName: "existing_bucket"
+      identity: "legacy_hmac_key_for_serviceaccount"
+      credential: "legacy_hmac_secret_for_serviceaccount+"
       path: "artifactory-ha/filestore"
-      bucketExists: false
+      bucketExists: true
```

**Anything else we need to know**:
```
artifactory@artifactory-artifactory-ha-primary-0:/opt/jfrog/artifactory$ cat /artifactory_bootstrap/binarystore.xml

<!-- Google storage -->
<config version="2">
    <chain>
        <provider id="cache-fs" type="cache-fs">
            <provider id="sharding-cluster" type="sharding-cluster">
                <readBehavior>crossNetworkStrategy</readBehavior>
                <writeBehavior>crossNetworkStrategy</writeBehavior>
                <redundancy>3</redundancy>
                <minSpareUploaderExecutor>2</minSpareUploaderExecutor>
                <sub-provider id="eventual-cluster" type="eventual-cluster">
                    <provider id="retry" type="retry">
                        <provider id="google-storage" type="google-storage"/>
                    </provider>
                </sub-provider>
                <dynamic-provider id="remote" type="remote"/>
                <property name="zones" value="local,remote"/>
            </provider>
        </provider>
    </chain>

    <!-- Set max cache-fs size -->
    <provider id="cache-fs" type="cache-fs">
        <maxCacheSize>5e+10</maxCacheSize>
        <cacheProviderDir>cache</cacheProviderDir>
    </provider>

    <provider id="eventual-cluster" type="eventual-cluster">
        <zone>local</zone>
    </provider>

    <provider id="remote" type="remote">
        <checkPeriod>30</checkPeriod>
        <timeout>10000</timeout>
        <zone>remote</zone>
    </provider>

    <provider id="file-system" type="file-system">
        <fileStoreDir>/var/opt/jfrog/artifactory/data/filestore</fileStoreDir>
        <tempDir>/tmp</tempDir>
    </provider>

    <provider id="google-storage" type="google-storage">
        <providerId>google-cloud-storage</providerId>
        <endpoint>storage.googleapis.com</endpoint>
        <httpsOnly>false</httpsOnly>
        <bucketName>existing_bucket</bucketName>
        <identity>legacy_hmac_key_for_serviceaccount</identity>
        <credential>legacy_hmac_secret_for_serviceaccount+</credential>
        <path>artifactory-ha/filestore</path>
        <bucketExists>true</bucketExists>
    </provider>
```
```
artifactory@artifactory-artifactory-ha-primary-0:/opt/jfrog/artifactory$ ls /artifactory_bootstrap/
artifactory.cluster.license  binarystore.xml              gcp.credentials.json         info
```
gcp.credentials.json and binarystore.xml look good. No idea why Artifactory is trying to access the "default" bucket `artifactory-ha-gcp`

**Comment by w9n** [comment]
found this:
```
artifactory@artifactory-artifactory-ha-primary-0:/opt/jfrog/artifactory$ grep -r artifactory-ha-gcp /
/var/opt/jfrog/artifactory/etc/artifactory/binarystore.xml:        <bucketName>artifactory-ha-gcp</bucketName>
```
