### ISSUE TITLE
How to apply Artifactory YAML Configuration?

### ISSUE THREAD

**Issue by mscholze86** [jfrog/charts#958]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): QUESTION / FEATURE REQUEST

**Version of Helm and Kubernetes**: 
Helm: v3.1.3, Kubernetes v1.18.3

**Which chart**: 
jfrog/artifactory --version 9.5.3

**What happened**:
I tried to apply global Artifactory configurations like baseurl, ldap and mail server settings (like described here: https://www.jfrog.com/confluence/display/JFROG/Artifactory+YAML+Configuration) via _systemYaml:_ directive in my values.yaml or also via _configMapName:_ artifactory.config.import.xml without success. The systemYaml: configuration is ignored, setup wizard appears at the ui. 

values.yaml:
```
...
  systemYaml: |
    configVersion: 1
    urlBase: https://example.com
    fileUploadMaxSizeMb: 150
    security:
      ldapSettings:
         ...
      ldapGroupSettings:
         ...
    mailServer:
      enabled: true
      artifactoryUrl: https://example.com
      from: no-reply@example.com
      host: examplehost
      username:
      password:
      port: 25
      subjectPrefix: "Notice"
      ssl: false
      tls: false
...
```

The way to do it via the xml config map let artifactory crash with NullPointerException. Also upating the version information in the config part of the xml to 3.0.3 doesn't fix it.

```
2020-06-18T09:49:10.558Z [jfrt ] [INFO ] [1ba9f1a6eea95902] [.a.d.r.CentralConfigReader:107] [art-init            ] - The current Artifactory config schema namespace is 'http://artifactory.jfrog.org/xsd/3.0.3' The provided config does not seem to be compliant with it.
2020-06-18T09:49:10.617Z [jfrt ] [INFO ] [1ba9f1a6eea95902] [o.a.d.r.CentralConfigReader:86] [art-init            ] - Converting artifactory.config.xml version from 'v223' to 'v303'
2020-06-18T09:49:10.661Z [jfrt ] [INFO ] [1ba9f1a6eea95902] [shingSchema1DockerConverter:25] [art-init            ] - Started EnablePushingSchema1DockerConverter
2020-06-18T09:49:10.661Z [jfrt ] [INFO ] [1ba9f1a6eea95902] [shingSchema1DockerConverter:32] [art-init            ] - Finished EnablePushingSchema1DockerConverter
2020-06-18T09:49:10.661Z [jfrt ] [INFO ] [1ba9f1a6eea95902] [FixGoDefaultLayoutConverter:25] [art-init            ] - Starting 'Go fix default repository layout' conversion
2020-06-18T09:49:10.668Z [jfrt ] [ERROR] [1ba9f1a6eea95902] [ctoryContextConfigListener:116] [art-init            ] - Application could not be initialized: null
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.artifactory.lifecycle.webapp.servlet.ArtifactoryContextConfigListener.configure(ArtifactoryContextConfigListener.java:250)
	at org.artifactory.lifecycle.webapp.servlet.ArtifactoryContextConfigListener$1.run(ArtifactoryContextConfigListener.java:112)
Caused by: org.springframework.beans.factory.BeanInitializationException: Failed to initialize bean 'org.artifactory.config.InternalCentralConfigService'.; nested exception is java.lang.NullPointerException
	at org.artifactory.spring.ArtifactoryApplicationContext.initReloadableBeans(ArtifactoryApplicationContext.java:288)
	at org.artifactory.spring.ArtifactoryApplicationContext.refresh(ArtifactoryApplicationContext.java:270)
	at org.artifactory.spring.ArtifactoryApplicationContext.<init>(ArtifactoryApplicationContext.java:160)
	... 6 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.artifactory.version.converter.v300.FixGoDefaultLayoutConverter.convert(FixGoDefaultLayoutConverter.java:30)
	at org.artifactory.version.XmlConverterUtils.createDoc(XmlConverterUtils.java:57)
	at org.artifactory.version.XmlConverterUtils.convert(XmlConverterUtils.java:67)
	at org.artifactory.version.XmlConverterUtils.convert(XmlConverterUtils.java:39)
	at org.artifactory.version.ArtifactoryConfigVersion.convert(ArtifactoryConfigVersion.java:497)
	at org.artifactory.descriptor.reader.CentralConfigReader.readAndConvert(CentralConfigReader.java:88)
	at org.artifactory.config.CentralConfigServiceImpl.getCurrentConfig(CentralConfigServiceImpl.java:307)
	at org.artifactory.config.CentralConfigServiceImpl.initCacheAndGetCurrent(CentralConfigServiceImpl.java:173)
	at org.artifactory.config.CentralConfigServiceImpl.init(CentralConfigServiceImpl.java:169)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.artifactory.storage.fs.lock.aop.LockingAdvice.invoke(LockingAdvice.java:76)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy207.init(Unknown Source)
	at org.artifactory.spring.ArtifactoryApplicationContext.initReloadableBeans(ArtifactoryApplicationContext.java:286)
	... 8 common frames omitted
```

artifactory.config.import.xml:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<config xmlns="http://artifactory.jfrog.org/xsd/2.2.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jfrog.org/xsd/artifactory-v2_2_3.xsd">
    <urlBase>https://example.com</urlBase>
    <fileUploadMaxSizeMb>150</fileUploadMaxSizeMb>
    <security>
        <ldapSettings>
            <ldapSetting>
                ...
            </ldapSetting>
        </ldapSettings>
        <ldapGroupSettings>
            ...
        </ldapGroupSettings>
    </security>
    <mailServer>
        <enabled>true</enabled>
        <artifactoryUrl>https://example.com</artifactoryUrl>
        <from>no-reply@example.com</from>
        <host>examplehost</host>
        <username/>
        <password/>
        <port>25</port>
        <subjectPrefix>Notice</subjectPrefix>
        <ssl>false</ssl>
        <tls>false</tls>
    </mailServer>
</config>
```

**What you expected to happen**:
Because of xml uglyness I thougt I can configure the artifactory basic settings via systemYaml directive in values.yaml and it will just work :)

**How to reproduce it** (as minimally and precisely as possible):
Try do deploy the helm chart with the configured systemYaml or config xml way in values.yaml.

**Anything else we need to know**:

**Comment by danielezer** [comment]
@mscholze86 [This](https://www.jfrog.com/confluence/display/JFROG/Artifactory+YAML+Configuration) is for REST API, this is not the `system.yaml`. The `system.yaml` is used for configuring the installation, while the REST API is used to create resources and set global configurations. Please take a look [here](https://www.jfrog.com/confluence/display/JFROG/Artifactory+YAML+Configuration#ArtifactoryYAMLConfiguration-ApplyingConfigurationChanges) for information about how to apply the yaml with the REST API.

**Comment by mscholze86** [comment]
@danielezer Thanks for your reply. So there is no other way to configure the LDAP and mail server configuration via Helm Chart? May a sidecar container can help. It waits for the REST API and then automatically does the configuration.

**Comment by danielezer** [comment]
Yes you can use a sidecar container for that, but you would have to provide the username and password/access token
